{
    "branches": [
        {
            "id": 1415,
            "branchType": {
                "id": 5,
                "code": "11",
                "name": "Филиал"
            },
            "shortName": "Хакасский региональный филиал",
            "name": "Хакасский региональный филиал",
            "geographicalRegion": null,
            "address": null,
            "lawAddress": null,
            "openDate": "2000-01-01",
            "closeDate": null,
            "bik": "049514767",
            "corAcc": "30101810700000000767",
            "registrationNumber": null,
            "phone": null,
            "fax": null,
            "phoneBusiness": null,
            "phoneNatural": null,
            "phoneCurrencyControl": null,
            "phoneCallCentre": null,
            "okpo": "56764330",
            "ogrn": null,
            "kpp": null,
            "inn": "7725114488",
            "branchCode": "3700",
            "upperBranchCode": null,
            "timeZone": "+07:00",
            "workSchedule": null,
            "gpsLatitude": 55.913586,
            "gpsLongitude": 42.148037,
            "range": null,
            "premiumService": false,
            "privateBanking": false,
            "sellingCoins": false,
            "buyingCoins": false,
            "bullionOperations": false,
            "preciousMetalsOperations": false,
            "serviceDisabledPeople": false,
            "barrierFree": false,
            "serviceDeafMutePeople": false,
            "equippedWithRamp": false,
            "equippedWithLift": false,
            "equippedWithElevator": false,
            "equippedWithStairclimber": false,
            "hasHelpMeButton": false,
            "retailId": null,
            "safeBoxCaseVolumes": null
        },
        {
            "id": 1230,
            "branchType": {
